const KNOWLEDGE_TAG_ALIASES = Object.freeze({
  "近义词辨析": Object.freeze(["近义词", "词义理解", "词义判断"]),
  "词义理解": Object.freeze(["词语理解", "词语运用"]),
  "词义辨析": Object.freeze(["词义理解", "词义判断", "词语理解"]),
  "词语搭配": Object.freeze(["量词搭配", "词语运用"]),
  "词语感情色彩": Object.freeze(["词语理解", "词语运用"]),
  "成语运用": Object.freeze(["成语理解", "词语运用"]),
  "句子结构": Object.freeze(["句意理解", "句意概括"]),
  "病句辨析": Object.freeze(["句意理解", "标点符号"]),
  "段落概括": Object.freeze(["句意概括", "课文理解", "短文推理"]),
  "说明文阅读": Object.freeze(["阅读理解", "阅读概括", "信息提取", "课文理解"]),
  "段落关系": Object.freeze(["阅读理解", "阅读概括", "结构判断", "段落理解", "课文理解"]),
  "中心句": Object.freeze(["阅读概括", "信息提取", "句意概括", "课文理解"]),
  "阅读理解": Object.freeze(["课文理解", "短文推理", "图表阅读", "通知理解", "留言理解"]),
  "阅读概括": Object.freeze(["主旨理解", "课文理解", "句意概括"]),
  "信息提取": Object.freeze(["图表阅读", "通知理解", "留言理解", "课文理解"]),
  "主题理解": Object.freeze(["主旨理解", "阅读概括", "课文理解"]),
  "中心思想": Object.freeze(["主旨理解", "阅读概括", "课文理解"]),
  "观点提取": Object.freeze(["主旨理解", "阅读概括", "课文理解"]),
  "古诗理解": Object.freeze(["古诗积累", "诗句理解"]),
  "文言启蒙": Object.freeze(["古文理解", "文言理解"]),
  "文言句意": Object.freeze(["古文理解", "文言理解"]),
  "古诗文理解": Object.freeze(["古诗积累", "古文理解", "文言理解", "诗句理解"]),
  "古诗文复习": Object.freeze(["古诗积累", "古文理解", "文言理解", "诗句理解"]),
  "诗句理解": Object.freeze(["古诗积累", "课文理解"]),
  "词句品味": Object.freeze(["词义理解", "词语理解", "句子理解", "句意理解", "修辞作用", "修辞理解"]),
  "表达效果": Object.freeze(["修辞作用", "句子理解", "句意理解", "修辞理解", "方法理解"]),
  "修辞作用": Object.freeze(["修辞理解", "句意理解", "方法理解"]),
  "修辞运用": Object.freeze(["修辞作用", "修辞理解", "修辞判断"]),
  "比喻句": Object.freeze(["修辞理解"]),
  "拟人句": Object.freeze(["修辞理解"]),
  "排比句": Object.freeze(["修辞理解"]),
  "语言赏析": Object.freeze(["修辞作用", "修辞理解", "句子理解", "句意理解", "方法理解"]),
  "情感体会": Object.freeze(["课文理解", "主旨理解", "情感变化"]),
  "人物描写": Object.freeze(["人物理解", "人物心理"]),
  "综合阅读": Object.freeze(["课文理解", "主旨理解", "图表阅读", "条件理解", "条件推断"]),
  "信息整合": Object.freeze(["顺序整合", "条件理解", "条件推断", "图表阅读"]),
  "传统文化": Object.freeze(["文学常识", "课文常识", "文体常识", "民间故事", "神话理解", "人物常识"]),
  "观察表达": Object.freeze(["看图说话", "看图写话", "写作方法"]),
  "写作顺序": Object.freeze(["写作方法", "顺序理解"]),
  "写事顺序": Object.freeze(["写作方法", "顺序理解"]),
  "习作起步": Object.freeze(["写作方法"]),
  "习作方法": Object.freeze(["写作方法"]),
  "习作结构": Object.freeze(["写作方法"]),
  "记事表达": Object.freeze(["写作方法"]),
  "场面描写": Object.freeze(["写作方法"]),
  "细节描写": Object.freeze(["写作方法"]),
  "写人表达": Object.freeze(["写作方法"]),
  "写景表达": Object.freeze(["写作方法"]),
  "表达顺序": Object.freeze(["顺序理解", "通知理解"]),
  "观点表达": Object.freeze(["表达交流", "演讲写作"]),
  "重点描写": Object.freeze(["写作方法"]),
  "习作复习": Object.freeze(["写作方法"]),
  "写作思路": Object.freeze(["写作方法", "演讲写作"]),
  "表达条理": Object.freeze(["写作方法", "通知理解"]),
  "写人写事写景": Object.freeze(["写作方法"]),
  "写话表达": Object.freeze(["写作方法"]),
  "表达方法": Object.freeze(["方法理解", "修辞理解", "文体常识"]),
  "句子理解": Object.freeze(["句意理解", "句意概括"]),
  "句型理解": Object.freeze(["句子理解", "句意理解", "句型判断"]),
  "句型替换": Object.freeze(["句型判断", "句子理解"]),
  "句型复习": Object.freeze(["句型判断", "句子理解"]),
  "句意判断": Object.freeze(["句意理解", "句子理解", "句型判断"]),
  "课堂用语": Object.freeze(["课堂指令", "情景对话", "句子选择"]),
  "日常交流": Object.freeze(["情景对话", "句子选择"]),
  "日常问答": Object.freeze(["情景对话", "句子选择"]),
  "个人信息": Object.freeze(["情景对话", "句子选择", "词义判断"]),
  "学校生活": Object.freeze(["情景对话", "句子选择", "词义判断"]),
  "校园生活": Object.freeze(["情景对话", "句子选择", "词义判断"]),
  "家庭成员": Object.freeze(["词义判断", "情景对话"]),
  "食物词汇": Object.freeze(["词义判断", "单词认读", "句意理解"]),
  "物品词汇": Object.freeze(["词义判断", "单词认读"]),
  "词汇认读": Object.freeze(["单词认读", "词义判断"]),
  "时间表达": Object.freeze(["时间词汇", "活动安排", "句意理解"]),
  "日程表达": Object.freeze(["时间词汇", "活动安排", "句意理解"]),
  "日常活动": Object.freeze(["活动安排", "情景对话"]),
  "旅行场景": Object.freeze(["情景对话", "活动安排", "句子选择"]),
  "计划安排": Object.freeze(["活动安排", "时间词汇", "句意理解"]),
  "人物关系": Object.freeze(["情景对话", "词义判断"]),
  "职业词汇": Object.freeze(["词义判断", "单词认读"]),
  "节日词汇": Object.freeze(["情景对话", "句子选择"]),
  "天气表达": Object.freeze(["情景对话", "句意理解"]),
  "天气词汇": Object.freeze(["情景对话", "句意理解"]),
  "位置表达": Object.freeze(["短语理解", "句子选择", "情景对话"]),
  "公共场所": Object.freeze(["短语理解", "句子选择", "情景对话"]),
  "健康表达": Object.freeze(["句意理解", "情景对话"]),
  "建议句型": Object.freeze(["句意理解", "情景对话"]),
  "路线理解": Object.freeze(["短语理解", "句子选择"]),
  "综合判断": Object.freeze(["阅读理解", "短文理解", "句型判断", "句子选择"]),
  "数位顺序表": Object.freeze(["数位认识", "数位判断"]),
  "数的改写": Object.freeze(["近似数"]),
  "大数认识": Object.freeze(["近似数", "数位认识"]),
  "万以内数": Object.freeze(["数位认识", "数字规律"]),
  "估算": Object.freeze(["估算判断", "综合计算", "多步计算"]),
  "情景计算": Object.freeze([
    "两步应用",
    "多步计算",
    "综合计算",
    "除法应用",
    "周长应用",
    "面积应用",
    "平均数应用",
    "圆周长应用",
    "圆柱应用",
    "圆锥应用",
    "折扣应用",
    "按比例分配",
    "按比分配"
  ]),
  "小数初步": Object.freeze(["单位换算", "小数认识", "小数应用", "小数比较", "小数计算"]),
  "小数意义": Object.freeze(["单位换算", "小数认识", "小数应用", "小数加法", "小数减法"]),
  "小数大小比较": Object.freeze(["小数比较", "数的比较", "小数加法", "小数减法"]),
  "因数与倍数": Object.freeze(["数字规律"]),
  "2和5的倍数特征": Object.freeze(["数字规律"]),
  "质数与合数": Object.freeze(["数字规律"]),
  "数的奇偶性": Object.freeze(["数字规律"]),
  "三位数乘两位数": Object.freeze(["乘法计算", "综合计算"]),
  "积的变化规律": Object.freeze(["数字规律", "综合计算"]),
  "除数是两位数的除法": Object.freeze(["除法计算", "综合计算"]),
  "试商": Object.freeze(["除法计算"]),
  "商的变化规律": Object.freeze(["数字规律", "除法计算"]),
  "平行与垂直": Object.freeze(["图形认识", "角的认识"]),
  "角的分类": Object.freeze(["角的认识", "角度判断"]),
  "顺序关系": Object.freeze(["顺序理解"]),
  "因果关系": Object.freeze(["关联词", "关联词理解", "关联词判断", "阅读理解"]),
  "单位换算": Object.freeze(["单位换算", "长度换算", "时间换算", "人民币换算"]),
  "长度单位": Object.freeze(["长度换算", "单位换算"]),
  "质量单位": Object.freeze(["单位换算"]),
  "加法运算律": Object.freeze(["加法速算", "综合计算", "多步计算"]),
  "乘法运算律": Object.freeze(["乘法速算", "综合计算", "多步计算"]),
  "简便计算": Object.freeze(["加法速算", "减法速算", "乘法速算", "除法速算", "综合计算", "多步计算"]),
  "混合运算": Object.freeze(["多步计算", "综合计算"]),
  "平行四边形": Object.freeze(["图形认识"]),
  "平行四边形面积": Object.freeze(["面积计算", "面积应用"]),
  "梯形面积": Object.freeze(["面积计算", "面积应用"]),
  "组合图形面积": Object.freeze(["面积计算", "面积应用"]),
  "用字母表示数": Object.freeze(["简易方程"]),
  "等式性质": Object.freeze(["简易方程"]),
  "三角形分类": Object.freeze(["三角形认识", "图形认识"]),
  "三角形特性": Object.freeze(["三角形认识", "图形认识"]),
  "三角形面积": Object.freeze(["面积公式", "面积计算", "面积应用"]),
  "图形认识": Object.freeze(["三角形认识", "角的认识"]),
  "条形统计图": Object.freeze(["图表分析", "图表阅读", "数据整理"]),
  "折线统计图": Object.freeze(["图表分析", "图表阅读", "统计整合"]),
  "数据整理": Object.freeze(["图表分析", "图表阅读", "统计整合", "数量统计"]),
  "平均数": Object.freeze(["平均数", "平均数应用"]),
  "分数意义": Object.freeze(["分数应用", "分数比较"]),
  "分数大小比较": Object.freeze(["分数比较", "分数应用"]),
  "真分数和假分数": Object.freeze(["分数比较", "分数应用"]),
  "分数单位": Object.freeze(["分数应用"]),
  "约分": Object.freeze(["分数计算", "分数应用"]),
  "通分": Object.freeze(["分数计算", "分数应用"]),
  "小数加法": Object.freeze(["小数计算", "小数应用"]),
  "分数加法": Object.freeze(["分数计算", "分数应用"]),
  "分数减法": Object.freeze(["分数计算", "分数加法", "分数应用"]),
  "分数乘法": Object.freeze(["分数应用", "分数计算", "分数速算"]),
  "倒数": Object.freeze(["分数计算", "分数速算"]),
  "分数除法": Object.freeze(["分数计算", "分数应用", "分数速算", "综合计算"]),
  "长方体认识": Object.freeze(["体积计算", "体积应用"]),
  "正方体认识": Object.freeze(["体积计算", "体积应用"]),
  "表面积": Object.freeze(["体积计算", "体积应用"]),
  "体积初步": Object.freeze(["体积计算", "体积应用"]),
  "百分数意义": Object.freeze(["百分数应用"]),
  "百分数与分数小数互化": Object.freeze(["百分数应用", "百分数基础", "单位换算"]),
  "比的意义": Object.freeze(["比的化简", "比的应用", "按比分配", "按比例分配"]),
  "比值": Object.freeze(["比的化简", "比的应用"]),
  "按比例分配": Object.freeze(["按比例分配", "按比分配", "比的应用"]),
  "数量关系": Object.freeze(["综合计算", "两步应用", "多步计算", "按比例分配", "按比分配"]),
  "比例": Object.freeze(["比例尺应用", "比例尺", "按比例分配", "按比分配", "综合计算"]),
  "正比例初步": Object.freeze(["比例尺应用", "图表分析"]),
  "反比例初步": Object.freeze(["比例尺应用", "图表分析"]),
  "圆锥认识": Object.freeze(["圆柱认识", "圆锥体积", "圆锥应用", "体积计算"]),
  "统计整理": Object.freeze(["统计整合", "图表分析", "数量统计"]),
  "总复习": Object.freeze(["综合计算", "图表阅读", "统计整合"]),
  "综合应用": Object.freeze(["综合计算"])
});

function normalizeKnowledgeTag(value) {
  return String(value || "").trim().replace(/\s+/g, " ");
}

function getKnowledgeTagSearchTerms(value) {
  const normalizedTag = normalizeKnowledgeTag(value);

  if (!normalizedTag) {
    return [];
  }

  return [...new Set([normalizedTag, ...(KNOWLEDGE_TAG_ALIASES[normalizedTag] || [])])];
}

module.exports = {
  KNOWLEDGE_TAG_ALIASES,
  getKnowledgeTagSearchTerms
};
